name: Example workflow for java with snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: snyk test
        run: npm install -g snyk && snyk auth
    
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
